version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  jobs:
    pre_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install
      - pip install -Ur docs/requirements.txt
